2024-09-13 22:34:48,984 : INFO : root : Loading config.
2024-09-13 22:34:48,987 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-09-13 22:34:48,988 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\636ce416879e362e618e72aa23ee7aae.mpf_cache
2024-09-13 22:34:49,067 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\dorus\OneDrive\Documents\Pinball\PortalPinball-V4.0\machinefolder\modes\attract\config\attract.yaml
2024-09-13 22:34:49,067 : INFO : ConfigProcessor : Loading config from file C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\modes\attract\config\attract.yaml.
2024-09-13 22:34:49,068 : INFO : ConfigProcessor : Loading config: C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\modes\attract\config\attract.yaml
2024-09-13 22:34:49,068 : INFO : ConfigProcessor : Loading config from file C:\Users\dorus\OneDrive\Documents\Pinball\PortalPinball-V4.0\machinefolder\modes\attract\config\attract.yaml.
2024-09-13 22:34:49,068 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\OneDrive\Documents\Pinball\PortalPinball-V4.0\machinefolder\modes\attract\config\attract.yaml
2024-09-13 22:34:49,070 : INFO : ConfigProcessor : Config file cache created: C:\Users\dorus\AppData\Local\Temp\88f25e45fa15743a3d93de98d7c6ca4c.mpf_cache
2024-09-13 22:34:49,071 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\d8bc63701c1a2ad1653a8cc5aec9548a.mpf_cache
2024-09-13 22:34:49,071 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\10d9290df991d16f66be8677f9ce93b5.mpf_cache
2024-09-13 22:34:49,072 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev4
2024-09-13 22:34:49,072 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2024-09-13-22-34-48-mpf-Gaming_Dorus.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False, 'full_logfile_path': 'C:\\Users\\dorus\\OneDrive\\Documents\\Pinball\\PortalPinball-V4.0\\machinefolder\\logs\\2024-09-13-22-34-48-mpf-Gaming_Dorus.log'}
2024-09-13 22:34:49,072 : INFO : Machine : MPF path: C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf
2024-09-13 22:34:49,072 : INFO : Machine : Machine path: C:\Users\dorus\OneDrive\Documents\Pinball\PortalPinball-V4.0\machinefolder
2024-09-13 22:34:49,072 : INFO : Machine : Platform: win32
2024-09-13 22:34:49,072 : INFO : Machine : Python executable location: C:\ProgramData\anaconda3\envs\mpfenv\python.exe
2024-09-13 22:34:49,072 : INFO : Machine : Python version: 3.12.4 (64-bit)
2024-09-13 22:34:49,073 : INFO : Machine : Initializing MPF...
2024-09-13 22:34:49,352 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-09-13 22:34:49,369 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-09-13 22:34:49,369 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-09-13 22:34:49,369 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev4', 'prev_value': None, 'change': True}
2024-09-13 22:34:49,369 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev4, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-09-13 22:34:49,369 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.4', 'prev_value': None, 'change': True}
2024-09-13 22:34:49,482 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-11-10.0.22631-SP0', 'prev_value': None, 'change': True}
2024-09-13 22:34:49,483 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2024-09-13 22:34:49,483 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '11', 'prev_value': None, 'change': True}
2024-09-13 22:34:49,483 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.22631', 'prev_value': None, 'change': True}
2024-09-13 22:34:49,483 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2024-09-13 22:34:49,483 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': 'C:\\Users\\dorus\\OneDrive\\Documents\\Pinball\\PortalPinball-V4.0\\machinefolder\\logs\\2024-09-13-22-34-48-mpf-Gaming_Dorus.log', 'prev_value': None, 'change': True}
2024-09-13 22:34:49,483 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-09-13 22:34:49,500 : INFO : EventManager : Event: ======'drop_target_bank_db_dropbank_up'====== Args={}
2024-09-13 22:34:49,500 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2024-09-13 22:34:49,500 : INFO : SwitchController : Found active switch: ('2-1-16', <Platform.Virtual>) <switch.s_trough1>
2024-09-13 22:34:49,500 : INFO : SwitchController : Found active switch: ('2-1-17', <Platform.Virtual>) <switch.s_trough2>
2024-09-13 22:34:49,500 : INFO : SwitchController : Found active switch: ('2-1-18', <Platform.Virtual>) <switch.s_trough3>
2024-09-13 22:34:49,500 : INFO : SwitchController : Found active switch: ('2-1-19', <Platform.Virtual>) <switch.s_trough4>
2024-09-13 22:34:49,502 : ERROR : ConfigValidator : Your config contains a value for the setting "sound_player:loopmode", but this is not a valid setting name.
2024-09-13 22:34:49,502 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...tting name.')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...tting name.')>)>
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\config_players\sound_player.py", line 24, in _validate_config_item
    device_settings = self.machine.config_validator.validate_config(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 345, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player mode_attract_started:sounds with settings {'SlowMusic': {'bus': 'music', 'loopmode': 1}} >> Your config contains a value for the setting "sound_player:loopmode", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)
2024-09-13 22:34:49,514 : INFO : Machine : Starting the main run loop.
2024-09-13 22:34:49,515 : INFO : Machine : Shutting down...
2024-09-13 22:34:49,516 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-09-13 22:34:50,532 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\machine.py", line 793, in _run_loop
    raise self._exception['exception']
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\config_players\sound_player.py", line 24, in _validate_config_item
    device_settings = self.machine.config_validator.validate_config(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 345, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player mode_attract_started:sounds with settings {'SlowMusic': {'bus': 'music', 'loopmode': 1}} >> Your config contains a value for the setting "sound_player:loopmode", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)
2024-09-13 22:34:50,545 : INFO : root : MPF run loop ended.
